// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCglXGkYCcKTLOIAayI9QhsTT1JNijZSbw',
    appId: '1:376771509119:web:fc037418a44afed74db84a',
    messagingSenderId: '376771509119',
    projectId: 'royal-ruckus',
    authDomain: 'royal-ruckus.firebaseapp.com',
    storageBucket: 'royal-ruckus.firebasestorage.app',
    measurementId: 'G-WTKR3ETEKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAarQbY7k2jRDc2P4JJN-B3EHtvJ3RG2ys',
    appId: '1:376771509119:android:f548643cac3a19a24db84a',
    messagingSenderId: '376771509119',
    projectId: 'royal-ruckus',
    storageBucket: 'royal-ruckus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OhaknVDDV0kpf27gVbUeOe3VnsVA0nM',
    appId: '1:376771509119:ios:efc3334328ca98904db84a',
    messagingSenderId: '376771509119',
    projectId: 'royal-ruckus',
    storageBucket: 'royal-ruckus.firebasestorage.app',
    iosBundleId: 'io.royalruckus.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-OhaknVDDV0kpf27gVbUeOe3VnsVA0nM',
    appId: '1:376771509119:ios:0a035250ba8c777b4db84a',
    messagingSenderId: '376771509119',
    projectId: 'royal-ruckus',
    storageBucket: 'royal-ruckus.firebasestorage.app',
    iosBundleId: 'com.example.jamtama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCglXGkYCcKTLOIAayI9QhsTT1JNijZSbw',
    appId: '1:376771509119:web:4bb06bf82a5b7da04db84a',
    messagingSenderId: '376771509119',
    projectId: 'royal-ruckus',
    authDomain: 'royal-ruckus.firebaseapp.com',
    storageBucket: 'royal-ruckus.firebasestorage.app',
    measurementId: 'G-HYK7ND6PV8',
  );

}